database:
  host: "localhost"
  port: 3306
  database: "whitelist"
  user: "root"
  password: "password"
  usessl: false
  properties:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 30000
    connectionTimeout: 30000
    maxLifetime: 1800000

messages:
  not_whitelisted: "You are not whitelisted on this server."
  internal-error: "发生了一个内部错误：{0}"
  reject-join-no-whitelist: ":( 此 ID 还未处于白名单中"
  reject-join-incorrect-cases: "您正在使用 {0} 加入服务器，但您申请的白名单为 {1}，请保持用户名大小写一致"
  wladd-bad-arguments: "参数错误：/wladd <玩家ID> <担保人（若无请填Unknown）> <审核批次号（担保或史前时代，请填 000）> <白名单添加备注>"
  wladd-success: "{0} (ID: {1}) 的白名单已成功添加"
  wladd-error-no-updates: "添加失败，此玩家可能已经有白名单了，使用 /wlquery <玩家ID> 查询白名单详情"
  wlremove-bad-arguments: "参数错误：/wlremove <玩家ID> <删除原因>"
  wlremove-error-no-updates: "删除失败，共 0 行数据被更新，指定要删除的玩家 ID 是否本就没有白名单？"
  wlremove-success: "{0} 的白名单已成功移除"
  wlquery-bad-arguments: "参数错误：/wlquery <玩家ID>"
  wlquery-entry: "ID: {0} - {1} - {2}\n担保人：{3} 操作员：{4}\n审核批次号：{5}\n描述：{6}\n删除于：{7} 删除操作员：{8}\n删除原因：{9}"
  wlquery-no-data: "没有在数据库中检索到任何有关数据"
  delete-time: "删除时间: {0}"



